# Generated by Django 5.0.2 on 2024-02-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskdetails',
            table='task_details',
        ),
    ]
