# Generated by Django 5.0.2 on 2024-02-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_photo_taskdetails_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='photos',
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.photo'),
        ),
    ]
