# Generated by Django 5.0.2 on 2024-02-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_taskdetails_photos_taskdetails_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetails',
            old_name='photo',
            new_name='photos',
        ),
    ]
